name: recon
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - numpy=1.23.2
  - pandas=1.4.3
  - matplotlib=3.4.3
  - scipy=1.9.0
  - umap-learn=0.5.3
  - editdistance=0.6.2
  - umi_tools=1.1.2
  - pip:
    - mappy==2.24
    - seaborn==0.12.2

